# With this query we're looking to see if a token exists given a token and a username
# and then return when the token is valid_till
query DoesTokenExist($token: String = "", $username: String = "") {
  password_reset(
    where: { token: { _eq: $token }, user: { username: { _eq: $username } } }
  ) {
    user {
      email
      username
    }
    valid_till
  }
}
