query AllProjectsList(
  $order_by: [project_order_by!] = { name: asc }
  $limit: Int = 10
  $offset: Int = 0
  $name_regex: String = ".*"
) {
  project(
    order_by: $order_by
    limit: $limit
    offset: $offset
    where: { name: { _iregex: $name_regex } }
  ) {
    id
    name
    description
    created_at
    slug
    lines_aggregate {
      aggregate {
        count
      }
    }
    translations_aggregate {
      aggregate {
        count
      }
    }
  }
}

query ProjectBySlug($slug: String = "") {
  project(where: { slug: { _eq: $slug } }) {
    created_at
    description
    id
    name
  }
}
